### ISSUE TITLE
针对密钥是解出来的16进制数据进行SM2解密报错

### ISSUE THREAD

**Issue by fss815** [lat751608899/sm2#1]
类型错误: Argument 1 passed to Lat\Ecc\Point::mul() must be an instance of GMP, string given, called in F:\server\hbmini\vendor\latzou\sm2\src\Sm2.php on line 74

**Comment by lat751608899** [comment]
代码示例发下

**Comment by fss815** [comment]
$data = json_encode([
            'a' => 1,
            'b' => 2,
            'c' => 3,
        ]);
        $key = '0451844d8f4e8881806f27169142f7e22932245af841d4b6c705e8e2b3adbb0041616dd0968910e76df6c4f6eb1d6f0ef11188b54bb09f47aa925c15d4ab13c119';
        $sm2 = new Sm2();
        $pubKey = new PublicKey();
        list($x, $y) = $pubKey->parseUncompressedPoint($key);
        $pubKey->setPoint(new Point($x, $y));
        $res = $sm2->pubEncrypt($pubKey, $data);
dump($res);
// sm2 解密
        $privKey = new PrivateKey();
        $privKey->setKey('0f3e3fb2b68197851656e805ddb9825b21b50d5e215894ca5dd5781fe4c4bea8');
        $a = $sm2->decrypt($privKey, $res);
        dump($a);
![image](https://user-images.githubusercontent.com/38677280/178626517-66ed1180-9df1-4c24-91c8-f96983f82f19.png)
![image](https://user-images.githubusercontent.com/38677280/178626517-66ed1180-9df1-4c24-91c8-f96983f82f19.png)
包是composer下载的V2.0

**Comment by fss815** [comment]
解密报错
